#! /usr/bin/env python  

  

import rospy  

import rospkg 

from std_srvs.srv import Empty, EmptyRequest 

  

rospack = rospkg.RosPack()  

rospy.init_node('service_client')  

rospy.wait_for_service('/move_bb8_in_circle')  

my_service = rospy.ServiceProxy('/move_bb8_in_circle', Empty) 

my_object = EmptyRequest() 

result = my_service() 

  
